### ISSUE TITLE
No sauna icon

### ISSUE THREAD

**Issue by zhouska** [drawbars37/BAWicons#2]
Hi there, according to list posted here: https://community.home-assistant.io/t/custom-icons-in-dashboard-how/492655/6, there should be a sauna icon available. However, I don't see it icons overview https://github.com/drawbars37/BAWicons/blob/main/Custom%20Icons%2012-Mar-2024.png. Any chance you could share it too, please?

**Comment by drawbars37** [comment]
Unfortunately, there is no sauna icon in my library; there never was one.  In fact, I cannot even tell you why the list in that thread includes the word 'sauna.'  The only explanation I can think of is that the OP wanted a sauna icon, and the word 'sauna' was accidentally pasted in my reply.  I replied with DIY instructions to create a custom icon library, which could include a sauna icon.  I have corrected the HA thread today.  Sorry for the confusion.

If you would like me to add a sauna icon to the next release (probably in June), please provide a link to a graphic that best represents a sauna to you.  Otherwise, I will look for one myself when the time arrives. 

Regards,
-BW

**Comment by drawbars37** [comment]
The sauna icon has been added to the library.

**Comment by zhouska** [comment]
> The sauna icon has been added to the library.

yes, I noticed. Thank you very much.
